# Learn more about working with Shopify TOML files with Gadget at https://docs.gadget.dev/guides/plugins/shopify/advanced-topics/shopify-app-toml

client_id = "eab75fad28d81025a6ef212ff3f2fd0e"
name = "lockdin-development"
application_url = "https://lockdin--development.gadget.app/api/shopify/install-or-render"
embedded = true

handle = "lockdin-development"
[auth]
redirect_urls = [ "https://lockdin--development.gadget.app/api/connections/auth/shopify/callback" ]

[access_scopes]
scopes = "read_customers, write_customers, write_orders, read_orders, write_products, read_products, read_draft_orders, write_fulfillments, read_fulfillments, write_inventory, read_inventory, write_merchant_managed_fulfillment_orders, read_merchant_managed_fulfillment_orders, write_draft_orders, write_payment_terms, read_payment_terms, write_purchase_options, read_purchase_options, read_product_listings, write_script_tags, read_script_tags, write_themes, read_themes"

[webhooks]
api_version = "2026-04"

[[webhooks.subscriptions]]
compliance_topics = [ "customers/data_request", "customers/redact", "shop/redact" ]
uri = "https://webhooks.gadget-services.net/shopify/v1?domain=lockdin--development.gadget.app"
topics = [ "shop/update", "app/uninstalled" ]
