# Learn more about working with Shopify TOML files with Gadget at https://docs.gadget.dev/guides/plugins/shopify/advanced-topics/shopify-app-toml

client_id = "f97b4ed1d0c6be666ec3652c22270041"
name = "lockdin-development"
application_url = "https://lockdin--development.gadget.app/api/shopify/install-or-render"
embedded = true

handle = "lockdin"
[auth]
redirect_urls = [ "https://lockdin--development.gadget.app/api/connections/auth/shopify/callback" ]

[access_scopes]
scopes = "read_all_orders, read_analytics, read_product_listings, write_customers, write_draft_orders, write_fulfillments, write_inventory, write_merchant_managed_fulfillment_orders, write_orders, write_payment_terms, write_products, write_script_tags, write_themes, read_customer_payment_methods, read_payment_mandate, write_payment_mandate, read_purchase_options, write_purchase_options"

[webhooks]
api_version = "2026-04"

[[webhooks.subscriptions]]
compliance_topics = [ "customers/data_request", "customers/redact", "shop/redact" ]
uri = "https://webhooks.gadget-services.net/shopify/v1?domain=lockdin--development.gadget.app"
topics = [ "shop/update", "app/uninstalled" ]
