// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/app": {
    params: {};
  };
  "/app/integrations": {
    params: {};
  };
  "/app/analytics": {
    params: {};
  };
  "/app/settings": {
    params: {};
  };
  "/app/create": {
    params: {};
  };
  "/app/orders": {
    params: {};
  };
  "/*": {
    params: {
      "*": string;
    };
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/app" | "/app/integrations" | "/app/analytics" | "/app/settings" | "/app/create" | "/app/orders" | "/*";
  };
  "routes/_app.tsx": {
    id: "routes/_app";
    page: "/" | "/app" | "/app/integrations" | "/app/analytics" | "/app/settings" | "/app/create" | "/app/orders";
  };
  "routes/_app._index.tsx": {
    id: "routes/_app._index";
    page: "/";
  };
  "routes/_app.app.tsx": {
    id: "routes/_app.app";
    page: "/app" | "/app/integrations" | "/app/analytics" | "/app/settings" | "/app/create" | "/app/orders";
  };
  "routes/_app.app.integrations.tsx": {
    id: "routes/_app.app.integrations";
    page: "/app/integrations";
  };
  "routes/_app.app.analytics.tsx": {
    id: "routes/_app.app.analytics";
    page: "/app/analytics";
  };
  "routes/_app.app.settings.tsx": {
    id: "routes/_app.app.settings";
    page: "/app/settings";
  };
  "routes/_app.app._index.tsx": {
    id: "routes/_app.app._index";
    page: "/app";
  };
  "routes/_app.app.create.tsx": {
    id: "routes/_app.app.create";
    page: "/app/create";
  };
  "routes/_app.app.orders.tsx": {
    id: "routes/_app.app.orders";
    page: "/app/orders";
  };
  "routes/$.tsx": {
    id: "routes/$";
    page: "/*";
  };
};

type RouteModules = {
  "root": typeof import("./web/root.tsx");
  "routes/_app": typeof import("./web/routes/_app.tsx");
  "routes/_app._index": typeof import("./web/routes/_app._index.tsx");
  "routes/_app.app": typeof import("./web/routes/_app.app.tsx");
  "routes/_app.app.integrations": typeof import("./web/routes/_app.app.integrations.tsx");
  "routes/_app.app.analytics": typeof import("./web/routes/_app.app.analytics.tsx");
  "routes/_app.app.settings": typeof import("./web/routes/_app.app.settings.tsx");
  "routes/_app.app._index": typeof import("./web/routes/_app.app._index.tsx");
  "routes/_app.app.create": typeof import("./web/routes/_app.app.create.tsx");
  "routes/_app.app.orders": typeof import("./web/routes/_app.app.orders.tsx");
  "routes/$": typeof import("./web/routes/$.tsx");
};